export const URL = {
    base: '/',
    login: '/login',
    registration: '/registration',
    home: '/home',
    current_workout: '/current-workout',
    add_set: '/current-workout/add-set',
    list_workouts: '/list-workouts',
    current_exercises: '/current-exercises',
    exercises_storage: '/exercises-storage',
    add_exercise: '/list-exercises/add-exercise',
    form_add_set: '/form-add-set',
    form_add_exercise: '/form-add-exercise',
    error: '*',
};
